name: CI
on: [push]

jobs:
  setup_and_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [7.4]
        moodle-version: ["MOODLE_401_STABLE"]
        plugin-repo: ["https://github.com/Lysa14/moodle-local_cnw_smartcohort.git"]
        plugin-name: ["cnw_smartcohort"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Install Composer
        run: |
          mkdir -p bin
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php --install-dir=bin --filename=composer
          php -r "unlink('composer-setup.php');"

      - name: Install Dependencies
        run: composer install

      - name: Download Moodle
        run: |
          wget https://github.com/moodle/moodle/archive/${{ matrix.moodle-version }}.zip
          unzip ${{ matrix.moodle-version }}.zip
          mv moodle-${{ matrix.moodle-version }} moodle

      - name: Install Moodle Plugin
        run: |
          cd moodle
          git clone ${{ matrix.plugin-repo }} mod/${{ matrix.plugin-name }}

      - name: Run PHPUnit Tests
        run: |
          cd moodle
          vendor/bin/phpunit mod/${{ matrix.plugin-name }}/tests


