name: CICD
on: [push]

jobs:
  test_php:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [7.4]
        moodle-version: ["MOODLE_401_STABLE"]
        plugin-repo: ["https://github.com/Lysa14/moodle-local_cnw_smartcohort.git"]
        plugin-name: ["cnw_smartcohort"]
        node-version: [14]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Install Composer
        run: |
          mkdir -p bin
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php --install-dir=bin --filename=composer
          php -r "unlink('composer-setup.php');"
     
      - name: Install Web Server (Apache)
        run: |
          sudo apt-get update
          sudo apt-get install -y apache2
          sudo systemctl start apache2
     

      
      - name: Download Moodle
        run: |
          mkdir moodle
          wget https://github.com/moodle/moodle/archive/${{ matrix.moodle-version }}.zip
          unzip ${{ matrix.moodle-version }}.zip
          mv moodle-${{ matrix.moodle-version }}  moodle

      - name: Install Moodle Plugin 
        run: |
          cd  moodle/moodle-${{ matrix.moodle-version }}/local
          git clone ${{ matrix.plugin-repo }} 
          cd ../../..
          

      - name: Install PHP and Extensions
        run: |
          sudo apt-get install -y php8.2 php8.2-cli php8.2-xml php8.2-simplexml php8.2-dom php8.2-curl php8.2-zip php8.2-gd
          sudo systemctl restart apache2
     
      - name: Restart Apach
        run : sudo systemctl restart apache2

      - name: Install Composer Dependencies
        run: |
          cd  moodle/moodle-${{ matrix.moodle-version }}/
          composer install --prefer-dist --no-progress --no-suggest
          export PATH=$PATH:./vendor/bin   
    
      - name: Install PHPUnit
        run: |
          sudo apt-get install -y wget
          wget https://phar.phpunit.de/phpunit-9.5.28.phar
          chmod +x phpunit-9.5.28.phar
          sudo mv phpunit-9.5.28.phar /usr/local/bin/phpunit
  



      - name: Run PHPUnit Tests
        run: |
          cd moodle/moodle-${{ matrix.moodle-version }}/local
          ls -R
          phpunit moodle-local_${{ matrix.plugin-name }}/tests/.


  test_angular:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js for Angular
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install Dependencies for Angular
        run: |
          npm install
      - name: Run Angular Tests
        run: |
          npm test

  test_react:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js for React
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install Dependencies for React
        run: |
          npm install
      - name: Run React Tests
        run: |
          npm test

  test_python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Dependencies for Python
        run: |
          pip install -r requirements.txt
      - name: Run Python Tests
        run: |
          python -m unittest discover -s tests

  test_cobol:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Cobol
        run: |
          #  Cobol setup commands here
      - name: Run Cobol Tests
        run: |
          # Cobol testing commands here

  test_javascript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js for JavaScript
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install Dependencies for JavaScript
        run: |
          npm install
      - name: Run JavaScript Tests
        run: |
          npm test

    

